spring.application.name=interviewprep
# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/interview_prep
spring.datasource.username=root
spring.datasource.password=PRANAV1@bpp

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Server Port
server.port=7777