spring.application.name=interviewprep
# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/interview_prep
spring.datasource.username=root
spring.datasource.password=PRANAV1@bpp

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Server Port
server.port=7777


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gnspranav6@gmail.com
spring.mail.password=azpy diuh llmt oodu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true